

version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git default-jre default-jdk wget python gcc clang libssl-dev repo rsync flex bison
           git config --global user.name "cahya03"
           git config --global user.email "cahya03r1@gmail.com"
           git clone https://github.com/cahya03/kernel_xiaomi_msm8953-4.9 --depth 1 mido
           cd mido
           chmod +x build.sh
           ./build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
